import { NAV_LOGO, NAV_ITEMS } from '../utils/constant/nav';
import './global.css';
import { Navigation, ThemeProvider } from '@archipelago/ui';

export const metadata = {
  title: 'Welcome to archipelago',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body className="relative left-1/2 z-50 -translate-x-1/2 w-[95%] md:w-3/4">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navigation logo={NAV_LOGO} items={NAV_ITEMS} />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
