import './global.css';
import { Navigation, ThemeProvider } from '@archipelago/ui';

export const metadata = {
  title: 'Welcome to archipelago',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navigation />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
